"""Markdown summary memo export."""
import logging
from datetime import datetime
from pathlib import Path
from typing import List

from ..models import Opportunity, RunStats

logger = logging.getLogger("geronimo.export.markdown")


def export_markdown(opportunities: List[Opportunity], stats: RunStats,
                    output_dir: str) -> str:
    """Generate a markdown summary memo."""
    output_path = Path(output_dir).expanduser()
    output_path.mkdir(parents=True, exist_ok=True)
    filepath = output_path / f"Agent_Geronimo_Summary_{datetime.now():%Y_%m_%d}.md"

    lines = [
        f"# Agent Geronimo — Funding Opportunity Report",
        f"**Generated:** {datetime.now():%Y-%m-%d %H:%M}",
        "",
        "## Run Summary",
        f"- Total opportunities discovered: **{stats.total_raw}**",
        f"- After deduplication: **{stats.total_deduped}**",
        f"- High-priority TSM opportunities: **{stats.high_priority_tsm}**",
        f"- High-priority GMU center opportunities: **{stats.high_priority_gmu}**",
        f"- Federal opportunities: **{stats.federal_count}**",
        f"- Foundation opportunities: **{stats.foundation_count}**",
        f"- Sources queried: **{stats.sources_queried}** ({stats.sources_successful} successful)",
        "",
    ]

    # Top TSM opportunities
    tsm_top = sorted(
        [o for o in opportunities if o.tsm_fit_score >= 15],
        key=lambda o: o.tsm_fit_score, reverse=True,
    )[:15]

    if tsm_top:
        lines.append("## Top TSM-Fit Opportunities")
        lines.append("")
        for i, opp in enumerate(tsm_top, 1):
            lines.append(f"### {i}. {opp.title}")
            lines.append(f"- **Funder:** {opp.funder}")
            lines.append(f"- **Type:** {opp.opportunity_type}")
            lines.append(f"- **TSM Score:** {opp.tsm_fit_score} | **GMU Score:** {opp.gmu_center_fit_score}")
            lines.append(f"- **Deadline:** {opp.deadline or 'TBD'}")
            lines.append(f"- **Award:** {opp.typical_award or 'See listing'}")
            if opp.listing_url:
                lines.append(f"- **URL:** [{opp.listing_url[:60]}...]({opp.listing_url})")
            if opp.suggested_proposal_angle:
                lines.append(f"- **Angle:** {opp.suggested_proposal_angle}")
            if opp.why_this_could_work:
                lines.append(f"- **Why it works:** {opp.why_this_could_work}")
            lines.append(f"- **Recommendation:** {opp.final_recommendation}")
            lines.append("")

    # Top GMU Center opportunities
    gmu_top = sorted(
        [o for o in opportunities if o.gmu_center_fit_score >= 15],
        key=lambda o: o.gmu_center_fit_score, reverse=True,
    )[:10]

    if gmu_top:
        lines.append("## Top GMU Center-Fit Opportunities")
        lines.append("")
        for i, opp in enumerate(gmu_top, 1):
            lines.append(f"### {i}. {opp.title}")
            lines.append(f"- **Funder:** {opp.funder}")
            lines.append(f"- **GMU Score:** {opp.gmu_center_fit_score}")
            lines.append(f"- **Deadline:** {opp.deadline or 'TBD'}")
            if opp.listing_url:
                lines.append(f"- **URL:** [{opp.listing_url[:60]}...]({opp.listing_url})")
            if opp.suggested_framing_gmu:
                lines.append(f"- **GMU Framing:** {opp.suggested_framing_gmu}")
            lines.append("")

    # Top funders summary
    funder_counts = {}
    for opp in opportunities:
        f = opp.funder or "Unknown"
        funder_counts[f] = funder_counts.get(f, 0) + 1
    top_funders = sorted(funder_counts.items(), key=lambda x: x[1], reverse=True)[:15]

    lines.append("## Top Funders by Volume")
    lines.append("")
    lines.append("| Funder | Opportunities |")
    lines.append("|--------|--------------|")
    for funder, count in top_funders:
        lines.append(f"| {funder} | {count} |")
    lines.append("")

    # Errors
    if stats.errors:
        lines.append("## Errors / Issues")
        lines.append("")
        for err in stats.errors[:10]:
            lines.append(f"- {err}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Agent Geronimo v1.0*")

    content = "\n".join(lines)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    logger.info(f"Markdown summary saved: {filepath}")
    return str(filepath)
